### ISSUE TITLE
Broken docker container image

### ISSUE THREAD

**Issue by baggiponte** [protectai/llm-guard#66]
When I run the docker container, it exits with an error.

```
docker run --init -ti -p 8001:8000 -e DEBUG=True laiyer/llm-guard-api:latest
```

<details>
<summary><i>Traceback</i></summary>

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 712, in _error_catcher
    yield
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 833, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(419241715 bytes read, 11930905 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 934, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 905, in read
    data = self._raw_read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 811, in _raw_read
    with self._error_catcher():
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/urllib3/response.py", line 729, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(419241715 bytes read, 11930905 more expected)', IncompleteRead(419241715 bytes read, 11930905 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 416, in main
    run(
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/app/app.py", line 199, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "/home/user/app/app.py", line 48, in create_app
    input_scanners, output_scanners = load_scanners_from_config(config, vault, scanners_config_file)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/app/config.py", line 57, in load_scanners_from_config
    get_input_scanner(
  File "/home/user/app/config.py", line 93, in get_input_scanner
    return input_scanners.get_scanner_by_name(scanner_name, scanner_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llm_guard/input_scanners/util.py", line 32, in get_scanner_by_name
    return Anonymize(**scanner_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llm_guard/input_scanners/anonymize.py", line 97, in __init__
    transformers_recognizer = get_transformers_recognizer(recognizer_conf, use_onnx)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llm_guard/input_scanners/anonymize_helpers/analyzer.py", line 76, in get_transformers_recognizer
    transformers_recognizer.load_transformer(use_onnx=use_onnx, **recognizer_conf)
  File "/usr/local/lib/python3.11/site-packages/llm_guard/input_scanners/anonymize_helpers/transformers_recognizer.py", line 115, in load_transformer
    self._load_pipeline(use_onnx)
  File "/usr/local/lib/python3.11/site-packages/llm_guard/input_scanners/anonymize_helpers/transformers_recognizer.py", line 119, in _load_pipeline
    self.pipeline = pipeline(
                    ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llm_guard/transformers_helpers.py", line 113, in pipeline
    return _pipeline_ner(model, onnx_model, use_onnx, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llm_guard/transformers_helpers.py", line 146, in _pipeline_ner
    tf_model = optimum_onnxruntime.ORTModelForTokenClassification.from_pretrained(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/optimum/onnxruntime/modeling_ort.py", line 626, in from_pretrained
    return super().from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/optimum/modeling_base.py", line 372, in from_pretrained
    return from_pretrained_method(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/optimum/onnxruntime/modeling_ort.py", line 493, in _from_pretrained
    model_cache_path, preprocessors = cls._cached_file(
                                      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/optimum/onnxruntime/modeling_ort.py", line 828, in _cached_file
    model_cache_path = hf_hub_download(
                       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1457, in hf_hub_download
    http_get(
  File "/usr/local/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 524, in http_get
    for chunk in r.iter_content(chunk_size=DOWNLOAD_CHUNK_SIZE):
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(419241715 bytes read, 11930905 more expected)', IncompleteRead(419241715 bytes read, 11930905 more expected))
```
</details>

**Comment by asofter** [comment]
Hey @baggiponte , thanks for reaching out. 

Can you please share more information about your environment? Is it Macbook M1 or something else? Does it break immediately after starting? 

It seems that Docker doesn't have enough storage to load models. I tried to run this command on my machine and had no errors.

**Comment by baggiponte** [comment]
Oh lol that might be it. Will prune everything and come back to it :)

**Comment by baggiponte** [comment]
heya, I pruned the whole docker partition and ran again the command but it failed. I am running on a M3 Mac.

**Comment by asofter** [comment]
Is it the same error? It needs quite a lot of space, can you check also the docker config if it has enough storage allocated?

**Comment by baggiponte** [comment]
Sorry, didn't have time yet to check. My instance has 60GB of disk but only 2 of RAM - that might be the problem.

**Comment by asofter** [comment]
We found another problem in our docker image which was fixed yesterday: https://github.com/laiyer-ai/llm-guard/commit/e12b9a334ab38169131e4f6da263ceec2231f496

**Comment by baggiponte** [comment]
Hey there! Sorry for popping up late. The breakdown is definitely due to the container having allocated too little RAM. I bumped mine from 2GB to 8GB and the download proceeds well beyond the point it used to (but stil crashes).

Perhaps providing an approximate memory usage could be of help. Both in the docs for the container image but also for the scanner - something like an attribute or a staticmethod that provides one.

Feel free to close this issue and/or move it to another one or a discussion.

**Comment by asofter** [comment]
Hey @baggiponte , will add that information to the doc. And actually we also realized the image is quite heavy, and we will optimize it with a few tricks.
