### ISSUE TITLE
The LLM-Guard API docker instance running on podman return the following error while using swagger UI and testing methods.

### ISSUE THREAD

**Issue by ajithbitspilani** [protectai/llm-guard#90]
The LLM-Guard API docker instance running on podman return the following error while using swagger UI and testing methods.

**To Reproduce**
Follow steps to run an instance in podman
podman pull docker.io/laiyer/llm-guard-api

**Expected behavior**
Podman runs and the swagger UI be used for testing

**Screenshots**
![image](https://github.com/protectai/llm-guard/assets/107347605/88de605f-c5f8-4d2a-b316-1797b379fbc5)

![image](https://github.com/protectai/llm-guard/assets/107347605/266146c2-a4d3-4528-98e1-ec3e175e94cb)

**Additional context**
Error logs below
DEBUG:llm-guard-api:Received analyze request: prompt='string'
WARNING:presidio-analyzer:Entity CUSTOM doesn't have the corresponding recognizer in language : en
INFO:llm-guard:Scanned prompt with the score: {'Anonymize': 0.0, 'BanCompetitors': 0.0, 'BanSubstrings': 0.0, 'BanTopics': 0.0, 'Code': 0.0, 'Language': 0.0, 'PromptInjection': 0.0, 'Regex': 0.0, 'Secrets': 0.0, 'Sentiment': 0.0, 'TokenLimit': 0.0, 'Toxicity': 0.0}. Elapsed time: 0.504167 seconds
INFO:     10.88.0.2:35310 - "POST /analyze/prompt HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/app/app.py", line 147, in analyze_prompt
    sanitized_prompt, results_valid, results_score = await asyncio.wait_for(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 454, in wait_for
    if timeout <= 0:
       ^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'str' and 'int'

**Comment by asofter** [comment]
Hey @ajithbitspilani , thanks for raising the issue. 

We've just released a new version, which fixes this issue and introduces many cool features to the API like auth and opentelemetry integration.

**Comment by ajithbitspilani** [comment]
> Hey @ajithbitspilani , thanks for raising the issue.
> 
> We've just released a new version, which fixes this issue and introduces many cool features to the API like auth and opentelemetry integration.

I pulled the API again from web site, getting following error upon running the container
docker pull laiyer/llm-guard-api

Upon running.
2024-02-11 23:00:29 Traceback (most recent call last):
2024-02-11 23:00:29   File "/home/user/.local/bin/llm_guard_api", line 5, in <module>
2024-02-11 23:00:29     from app.app import run_app
2024-02-11 23:00:29   File "/home/user/.local/lib/python3.11/site-packages/app/app.py", line 25, in <module>
2024-02-11 23:00:29     from util import configure_logger
2024-02-11 23:00:29 ModuleNotFoundError: No module named 'util'

**Comment by asofter** [comment]
Oh, good catch. Thank you. I updated the image with the fix

**Comment by ajithbitspilani** [comment]
> Oh, good catch. Thank you. I updated the image with the fix

The API runs now as container deployment, thanks for that. but I could not find swagger UI up in /docs
I found /readyz and /health reporting good, but other routes are not up for example below:
![image](https://github.com/protectai/llm-guard/assets/107347605/244d2f13-6afc-427d-9dcf-fa3186195e07)

I found Swagger UI was up and running last time, I checked, but failed in code. In this version, the container is up and running, there is a security authentication failing me to bring up the input scan and output scan.

**Comment by asofter** [comment]
In order to call /analyze/prompt or /analyze/output, you need to send POST requests.

To get Swagger UI, you need to set LOG_LEVEL as DEBUG.

**Comment by asofter** [comment]
You can also remove `auth` config from the `scanners.yml` to not have it

**Comment by ajithbitspilani** [comment]
> You can also remove `auth` config from the `scanners.yml` to not have it

Thanks for quick response. I downloaded direct image and ran, so could not configure it out of the box, 
however, I will run from the code and let you know how it works.

**Comment by ajithbitspilani** [comment]
I am able to build docker container removing the auth section and it works now.
Requested a feature to expose the interface details and sample implementation code. 
Thank you.

**Comment by wangzuohao** [comment]
I run the container directly, with DEBUG log level and do not enable auth in the command line. I also login the docker and make sure the auth is disabled in the scanners.yml:
# docker run -d -p 8000:8000 -e LOG_LEVEL='DEBUG'  laiyer/llm-guard-api:latest

but I can not access the swagger.json:

{
    "message": "Not Found",
    "details": null
}

Am I missing something?
